import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { foundations } from "@ai-ds/foundations";
import { semanticTokens, resolveThemes } from "@ai-ds/semantic-tokens";
import { accessibilityPolicy, assertAccessibleThemes } from "@ai-ds/accessibility";
import { buttonPrimitive, textFieldPrimitive } from "@ai-ds/primitives";
import { recipes } from "@ai-ds/recipes";
import { patterns } from "@ai-ds/patterns";
import { compositions } from "@ai-ds/compositions";

const themes = resolveThemes(foundations);
const validation = assertAccessibleThemes(themes);
const variable = name => `--ds-${name.replaceAll(".", "-")}`;
const block = (selector, theme) => `${selector} {\n${Object.entries(theme).map(([name, token]) => `  ${variable(name)}: ${Array.isArray(token.$value) ? token.$value.join(", ") : token.$value};`).join("\n")}\n}`;
const css = `/* Generated by @ai-ds/orchestrator. Edit source tokens, not this file. */\n${block(":root, [data-theme=\"light\"]", themes.light)}\n\n${block("[data-theme=\"dark\"]", themes.dark)}\n`;
const manifest = {
  schemaVersion: 1,
  instruction: "Use listed semantic token names and component variants only; change source modules rather than generated files.",
  themes,
  tokenDefinitions: semanticTokens,
  accessibility: { policy: accessibilityPolicy, validation },
  primitives: [buttonPrimitive, textFieldPrimitive],
  recipes,
  patterns,
  compositions
};
const json = `${JSON.stringify(manifest, null, 2)}\n`;
const here = path.dirname(fileURLToPath(import.meta.url));
const output = path.resolve(here, "../../../apps/demo/public/generated");
const files = [["tokens.css", css], ["design-system.manifest.json", json]];

await mkdir(output, { recursive: true });
if (process.argv.includes("--check")) {
  for (const [name, content] of files) {
    const existing = await readFile(path.join(output, name), "utf8").catch(() => "");
    if (existing !== content) throw new Error(`${name} is stale. Run npm run generate.`);
  }
  console.log("Generated artifacts are current and accessible.");
} else {
  await Promise.all(files.map(([name, content]) => writeFile(path.join(output, name), content)));
  console.log(`Generated ${files.length} validated artifacts in ${output}`);
}

